### PR TITLE
fix: restore selections *after* the file save

### LINKED ISSUE #396: Changes are applied to the file after manual saving when `insert_final_newline` is `true`
Hello,

For some files, when we save them (Ctrl+S), they still appear as unsaved, even though they are actually saved.

. However, if we disable EditorConfig in VS Code, the issue disappears.

Image

Thanks.

### PR DESCRIPTION
**Pull request by SunsetTechuila**
Please fill in this template.

- [x] Use a meaningful title for the pull request.
- [x] Use meaningful commit messages.
- [x] Run `tsc` w/o errors (same as `npm run build`).
- [x] Run `npm run lint` w/o errors.

fixes #396

### CODE REVIEW

**Comment by SunsetTechuila** [comment]
the problem with the #372 is that it doesn't [pause the event loop to apply changes](https://code.visualstudio.com/api/references/vscode-api?source=post_page---------------------------#TextDocumentWillSaveEvent.waitUntil), which works only with autosave enabled

and #386 doesn't fix any "race condition", it just gives more time to re-save the file

File: src/DocumentWatcher.ts [hunk 1]
```diff
@@ -64,6 +65,11 @@ export default class DocumentWatcher {
 
 		subscriptions.push(
 			workspace.onDidSaveTextDocument(doc => {
+				const activeEditor = window.activeTextEditor
```
Comment (SunsetTechuila) [inline src/DocumentWatcher.ts:68]: it is **technically** possible that it can be changed during saving, but this is very unlikely
