### PR TITLE
Fix unhandled error when generating .editorconfig

### LINKED ISSUE #253: Cannot read property 'toString' of undefined
- [✓ ] I have a question that is specific to this extension; thus, inappropriate for the main [EditorConfig issue tracker](https://github.com/editorconfig/editorconfig/issues).
- [ ✓] I tried running `code --disable-extensions` and the issue did **NOT** present itself.

## Issue

|                   |  os                    | Visual Studio Code | editorconfig-vscode |
|-------------|------------------|--------------------|---------------------|
| **Version**| win10pro 1909  | 1.39.2                  | 0.14.2                    |

## description
When I use the command generator .editorconfig, the plugin reports the error message as title.
screenshot

### PR DESCRIPTION
**Pull request by rdumont**
It was possible for the URI parameter to be `undefined`, so I've handled that scenario while accounting for the possibility of not being inside a folder (which the command binding should already prevent anyway).

Fixes #253.

---

Please fill in this template.

- [x] Use a meaningful title for the pull request.
- [x] Use meaningful commit messages.
- [x] Run `tsc` w/o errors (same as `npm run compile`).
- [x] Run `npm run lint` w/o errors.

### CODE REVIEW

File: src/commands/generateEditorConfig.ts [hunk 1]
```diff
@@ -5,7 +5,15 @@ import { FileType, Uri, window, workspace } from 'vscode'
  * current vscode settings.
  */
 export async function generateEditorConfig(uri: Uri) {
-	const editorConfigUri = Uri.parse(`${uri.toString()}/.editorconfig`)
+	const workspaceUri =
+		workspace.workspaceFolders && workspace.workspaceFolders[0].uri
+	const currentUri = uri || workspaceUri
+	if (!currentUri) {
+		window.showErrorMessage("Workspace doesn't contain any folders.")
```
Comment (jedmao) [inline src/commands/generateEditorConfig.ts]: I'm not understanding why it matters if the workspace doesn't contain any folders. What's the issue with that?

Comment (jedmao) [reply src/commands/generateEditorConfig.ts]: Under what scenario would you not be under a folder? Like when you just open vscode and haven't opened anything yet?

Comment (rdumont) [reply src/commands/generateEditorConfig.ts]: This situation should never happen because according to the [command definition](https://github.com/editorconfig/editorconfig-vscode/blob/08d184d50a74f383367a8272680cde208a17b7ad/package.json#L49) it should only be available when inside a folder.

I simply added an error message to gracefully handle the situation in a freak edge case.

> I'm not understanding why it matters if the workspace doesn't contain any folders. What's the issue with that?

Maybe the error message that I wrote wasn't clear enough about what I explained just now. Do you have a suggestion for making it clearer?

> Under what scenario would you not be under a folder? Like when you just open vscode and haven't opened anything yet?

Yes, that would be exactly the scenario, even though it should never happen in the real world.

Comment (rdumont) [reply src/commands/generateEditorConfig.ts]: Is this what is breaking the tests under linux? I wish I could see the pipeline output, but I don't have permission to access it.

Comment (jedmao) [reply src/commands/generateEditorConfig.ts]: I switched everything over the GitHub Actions and all is well! Thanks for the PR!
